/*
 * Medicine Inventory API
 *
 * Medicine inventory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medicine

import (
	"github.com/gin-gonic/gin"
)

type MedicineInventoryAPI interface {

	// DeleteMedicineInventoryEntry Delete /api/medicine-inventory/:ambulanceId/entries/:entryId
	// Deletes specific entry
	DeleteMedicineInventoryEntry(c *gin.Context)

	// GetMedicineInventoryEntries Get /api/medicine-inventory/:ambulanceId/entries
	// Provides the ambulance medicine inventory
	GetMedicineInventoryEntries(c *gin.Context)

	// GetMedicineInventoryEntry Get /api/medicine-inventory/:ambulanceId/entries/:entryId
	// Provides details about ambulance medicine inventory entry
	GetMedicineInventoryEntry(c *gin.Context)

	// UpdateMedicineInventoryEntry Put /api/medicine-inventory/:ambulanceId/entries/:entryId
	// Updates specific entry
	UpdateMedicineInventoryEntry(c *gin.Context)
}
