/*
 * Medicine Inventory API
 *
 * Medicine inventory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medicine

import (
	"github.com/gin-gonic/gin"
)

type OrderStatusesAPI interface {

	// GetStatus Get /api/medicine-order/statuses/:statusId
	// Provides the list of valid statuses for the order
	GetStatus(c *gin.Context)

	// GetStatuses Get /api/medicine-order/statuses
	// Provides the list of valid statuses for the order
	GetStatuses(c *gin.Context)
}
