/*
 * Medicine Inventory API
 *
 * Medicine inventory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medicine

// Status - Describes status order
type Status struct {

	// Unique identifier of the status
	Id int32 `json:"id,omitempty"`

	Value string `json:"value"`

	ValidTransitions []int32 `json:"validTransitions,omitempty"`
}
