/*
 * Medicine Inventory API
 *
 * Medicine inventory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package medicine

type MedicineOrderEntry struct {

	// Unique id of the entry in this medicine inventory
	Id string `json:"id"`

	// Name of medicine in medicine inventory
	Name string `json:"name,omitempty"`

	// Unique identifier of the medicine known to Web-In-Cloud system
	MedicineId string `json:"medicineId"`

	// Medicine count in the ambulance medicine inventory. It is a number of packages in the medicine inventory for the given ambulance.
	Count int32 `json:"count"`

	Status Status `json:"status"`
}
