# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and Publish WebApi Container Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v1*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  {} # allow manually trigger workflow

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Go version from go.mod
      id: get_go_version
      run: echo "go_version=$(grep -m1 'go ' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.get_go_version.outputs.go_version }}
    - name: openapi-generator-generate-action
      # You may pin to the exact commit or the version.
      # uses: craicoverflow/openapi-generator-generate-action@f5cb8c4751e164eab904995688909966bd1f36eb
      uses: craicoverflow/openapi-generator-generate-action@v1.2.1
      with:
        # The name of the generator to use
        generator: go-gin-server
        # OpenAPI specification file to use as the source for generation
        input: api/medicine.openapi.yaml
        # Provide a config object of additional properties
        additional-properties: apiPath=internal/medicine,packageName=medicine,interfaceOnly=true
              

    - name: Build
      run: go build -v ./cmd/medicine-api-service

    - name: Test
      run: go test -v ./...
    - name: Docker Setup QEMU
      # You may pin to the exact commit or the version.
      # uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      uses: docker/setup-qemu-action@v3.6.0
    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      uses: docker/setup-buildx-action@v3.10.0
    - name: Docker Metadata action
      # You may pin to the exact commit or the version.
      # uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        # List of Docker images to use as base name for tags
        images: undy45/medicine-webapi
        # List of tags as key-value pair attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      uses: docker/login-action@v3.4.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Debug Metadata output
      run: 'echo "Generated tags: ${{ steps.meta.outputs.tags }}"'
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        # Path to the Dockerfile
        file: ./build/docker/Dockerfile
        # List of metadata for an image
        labels: ${{ steps.meta.outputs.labels }}
        # List of target platforms for build
        platforms: linux/amd64,linux/arm64/v8
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: ${{ steps.meta.outputs.tags }}
              

              
